name: Dingtalk notify
description: Send notification to dingtalk custom bot
author: northwang

inputs:
  access_token:
    description: Dingtalk webhook access token
    required: true
  secret:
    description: Dingtalk webhook secret for sign
    required: false
  payload:
    description: Dingtalk webhook request json style body. More usage to see https://open.dingtalk.com/document/group/custom-robot-access
    required: true

outputs:
  response:
    description: Dingtalk webhook response

runs:
  using: docker
  image: Dockerfile