name: dingtalk-notifiy
description: Send notification to dingtalk custom bot
author: northwang

branding:
  icon: send
  color: blue

inputs:
  access_token:
    description: DingTalk webhook access token
    required: true
  secret:
    description: DingTalk webhook secret for sign
    required: false
  payload:
    description: DingTalk webhook request json style body. More usage to see https://open.dingtalk.com/document/group/custom-robot-access
    required: true

outputs:
  response:
    description: DingTalk webhook response

runs:
  using: docker
  image: Dockerfile